model:
  name: "unsloth/Qwen3-8B-unsloth-bnb-4bit" 
  max_seq_length: 4096
  dtype: null
  load_in_4bit: true
  trust_remote_code: true
  use_cache: false
  
  lora:
    r: 8
    alpha: 8
    dropout: 0.0
    bias: "none"
    target_modules: [
      "q_proj", "k_proj", "v_proj", "o_proj",
      "gate_proj", "up_proj", "down_proj"
    ]
    gradient_checkpointing: "unsloth"
    random_state: 42
    use_rslora: true
    loftq_config: null

training:
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 8
  num_train_epochs: 1
  learning_rate: 0.0001
  max_steps: -1
  
  gradient_checkpointing: true
  optimizer: "adamw_8bit"
  bf16: true
  fp16: false
  
  warmup_steps: 1000
  warmup_ratio: 0.03
  lr_scheduler_type: "cosine"
  
  logging_steps: 100
  save_strategy: "steps"
  save_steps: 1000
  save_total_limit: 10
  report_to: "none"
  
  packing: false
  seed: 42

dataset:
  path: "devops-42k/devops-42k.jsonl"
  format: "jsonl"
  conversation_format: "chatml"
  max_length: 4096
  subset_size: 0

hardware:
  device_map: "auto"
  environment_variables:
    PYTORCH_CUDA_ALLOC_CONF: "max_split_size_mb:256"
    TOKENIZERS_PARALLELISM: "false"
    CUDA_VISIBLE_DEVICES: "0"

smart_training:
  enable_loss_early_stopping: true
  early_stop_patience: 30
  early_stop_min_delta: 0.005
  early_stop_min_steps: 300
  early_stop_check_interval: 25
  
  target_loss: 0.3
  max_time_minutes: 3000000
  max_steps: null
  
  dataset_num_proc: 4

output:
  directory: "./qwen-kubernetes-0.0.8"
  save_method: "merged_16bit"
  
  test_prompts:
    - "How do I create a Kubernetes deployment with 3 replicas and resource limits?"
    - "What's the difference between a Service and an Ingress in Kubernetes?"
    - "How can I debug a pod that's stuck in Pending state?"
    - "Explain Kubernetes ConfigMaps and Secrets with examples"
    - "How do I set up horizontal pod autoscaling based on CPU usage?"